# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Category.create(code:0, name: "Generalidades")
Category.create(code:100, name: "Filosofía y psicología")
Category.create(code:200, name: "Religión")
Category.create(code:300, name: "Ciencias sociales")
Category.create(code:400, name: "Lenguas")
Category.create(code:500, name: "Matemáticas y ciencias naturales")
Category.create(code:600, name: "Tecnología y ciencias aplicadas")
Category.create(code:700, name: "Artes")
Category.create(code:800, name: "Literatura")
Category.create(code:900, name: "Historia y geografía")


	Subcategory.create(code:10, name: "Bibliografía", category_id: 1)
	Subcategory.create(code:20, name: "Bibliotecnología e informática", category_id: 1)
	Subcategory.create(code:30, name: "Enciclopedias generales", category_id: 1)
	Subcategory.create(code:50, name: "Publicaciones en serie", category_id: 1)
	Subcategory.create(code:60, name: "Organizaciones y museografía", category_id: 1) 
	Subcategory.create(code:70, name: "Periodismo, editoriales, diarios", category_id: 1)
	Subcategory.create(code:80, name: "Colecciones generales", category_id: 1)
	Subcategory.create(code:90, name: "Manuscritos y libros raros", category_id: 1)

	Subcategory.create(code:110, name: "Metafísica", category_id: 2)
	Subcategory.create(code:120, name: "Conocimiento, causa, fin, hombre", category_id: 2)
	Subcategory.create(code:130, name: "Parapsicología, ocultismo", category_id: 2)
	Subcategory.create(code:140, name: "Puntos de vista filosóficos", category_id: 2)
	Subcategory.create(code:150, name: "Psicología", category_id: 2)
	Subcategory.create(code:160, name: "Lógica", category_id: 2) 
	Subcategory.create(code:170, name: "Ética (filosofía moral)", category_id: 2)
	Subcategory.create(code:180, name: "Filosofía antigua, medieval, oriental", category_id: 2)
	Subcategory.create(code:190, name: "Filosofía moderna occidental", category_id: 2)

	Subcategory.create(code:210, name: "Religión natural", category_id: 3)
	Subcategory.create(code:220, name: "Biblia", category_id: 3)
	Subcategory.create(code:230, name: "Teología cristiana", category_id: 3)
	Subcategory.create(code:240, name: "Moral y prácticas cristianas", category_id: 3)
	Subcategory.create(code:250, name: "Iglesia local y órdenes religiosas", category_id: 3)
	Subcategory.create(code:260, name: "Teología social y eclesiología", category_id: 3) 
	Subcategory.create(code:270, name: "Historia y geografía de la iglesia", category_id: 3)
	Subcategory.create(code:280, name: "Credos de la iglesia cristiana", category_id: 3)
	Subcategory.create(code:290, name: "Otras religiones", category_id: 3)

	Subcategory.create(code:310, name: "Religión natural", category_id: 4)
	Subcategory.create(code:320, name: "Biblia", category_id: 4)
	Subcategory.create(code:330, name: "Teología cristiana", category_id: 4)
	Subcategory.create(code:340, name: "Moral y prácticas cristianas", category_id: 4)
	Subcategory.create(code:350, name: "Iglesia local y órdenes religiosas", category_id: 4)
	Subcategory.create(code:360, name: "Teología social y eclesiología", category_id: 4) 
	Subcategory.create(code:370, name: "Historia y geografía de la iglesia", category_id: 4)
	Subcategory.create(code:380, name: "Credos de la iglesia cristiana", category_id: 4)
	Subcategory.create(code:390, name: "Otras religiones", category_id: 4)

	Subcategory.create(code:410, name: "Lingüística", category_id: 5)
	Subcategory.create(code:420, name: "Inglés y anglosajón", category_id: 5)
	Subcategory.create(code:430, name: "Lenguas germánicas; alemán", category_id: 5)
	Subcategory.create(code:440, name: "Lenguas romances; francés", category_id: 5)
	Subcategory.create(code:450, name: "Italiano, rumano, rético", category_id: 5)
	Subcategory.create(code:460, name: "Español y portugués", category_id: 5) 
	Subcategory.create(code:470, name: "Lenguas itálicas; latín", category_id: 5)
	Subcategory.create(code:480, name: "Lenguas helénicas; griego clásico", category_id: 5)
	Subcategory.create(code:490, name: "Otras lenguas", category_id: 5)

	Subcategory.create(code:510, name: "Matemáticas", category_id: 6)
	Subcategory.create(code:520, name: "Astronomía y ciencias afines", category_id: 6)
	Subcategory.create(code:530, name: "Física", category_id: 6)
	Subcategory.create(code:540, name: "Química y ciencias afines", category_id: 6)
	Subcategory.create(code:550, name: "Geociencias", category_id: 6)
	Subcategory.create(code:560, name: "Paleontología", category_id: 6) 
	Subcategory.create(code:570, name: "Ciencias biológicas", category_id: 6)
	Subcategory.create(code:580, name: "Ciencias botánicas", category_id: 6)
	Subcategory.create(code:590, name: "Ciencias zoológicas", category_id: 6)

	Subcategory.create(code:610, name: "Ciencias médicas", category_id: 7)
	Subcategory.create(code:620, name: "Ingeniería y operaciones afines", category_id: 7)
	Subcategory.create(code:630, name: "Agricultura y tecnologías afines", category_id: 7)
	Subcategory.create(code:640, name: "Economía doméstica", category_id: 7)
	Subcategory.create(code:650, name: "Servicios administrativos empresariales", category_id: 7)
	Subcategory.create(code:660, name: "Química industrial", category_id: 7) 
	Subcategory.create(code:670, name: "Manufacturas", category_id: 7)
	Subcategory.create(code:680, name: "Manufacturas varias", category_id: 7)
	Subcategory.create(code:690, name: "Construcciones", category_id: 7)

	Subcategory.create(code:710, name: "Urbanismo y arquitectura del paisaje", category_id: 8)
	Subcategory.create(code:720, name: "Arquitectura", category_id: 8)
	Subcategory.create(code:730, name: "Artes plásticas; escultura", category_id: 8)
	Subcategory.create(code:740, name: "Dibujo, artes decorativas y menores", category_id: 8)
	Subcategory.create(code:750, name: "Pintura y pinturas", category_id: 8)
	Subcategory.create(code:760, name: "Artes gráficas; grabados", category_id: 8) 
	Subcategory.create(code:770, name: "Fotografía y fotografías", category_id: 8)
	Subcategory.create(code:780, name: "Música", category_id: 8)
	Subcategory.create(code:790, name: "Entretenimiento", category_id: 8)

	Subcategory.create(code:810, name: " Literatura americana en inglés", category_id: 9)
	Subcategory.create(code:820, name: "Literatura inglesa y anglosajona", category_id: 9)
	Subcategory.create(code:830, name: "Literaturas germánicas", category_id: 9)
	Subcategory.create(code:840, name: "Literaturas de las lenguas romances", category_id: 9)
	Subcategory.create(code:850, name: "Literaturas italiana, rumana", category_id: 9)
	Subcategory.create(code:860, name: "Literaturas española y portuguesa", category_id: 9) 
	Subcategory.create(code:870, name: "Literaturas de las lenguas itálicas", category_id: 9)
	Subcategory.create(code:880, name: "Literaturas de las lenguas helénicas", category_id: 9)
	Subcategory.create(code:890, name: "Literaturas de otras lenguas", category_id: 9)

	Subcategory.create(code:910, name: "Geografía; viajes", category_id: 10)
	Subcategory.create(code:920, name: "Biografía y genealogía", category_id: 10)
	Subcategory.create(code:930, name: "Historia del mundo antiguo", category_id: 10)
	Subcategory.create(code:940, name: "Historia de Europa", category_id: 10)
	Subcategory.create(code:950, name: "Historia de Asia", category_id: 10)
	Subcategory.create(code:960, name: "Historia de África", category_id: 10) 
	Subcategory.create(code:970, name: "Historia de América del Norte", category_id: 10)
	Subcategory.create(code:980, name: "Historia de América del Sur", category_id: 10)
	Subcategory.create(code:990, name: "Historia de otras regio", category_id: 10)